name: Flutter Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source code
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "17"
          cache: "gradle"

      - name: Verify java version
        run: java -version

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.27.3"
          cache: true

      - name: Verify flutter version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze the code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --debug
